import { ContentText, Language, Song } from './types';

export const TRANSLATIONS: Record<Language, ContentText> = {
  [Language.RU]: {
    nav_home: "Главная",
    nav_about: "О боте",
    nav_features: "Возможности",
    nav_charts: "Топ-чарты",
    nav_contact: "Контакты",
    hero_title: "MusicSearch Ru — быстрый поиск музыки",
    hero_subtitle: "Официальный сервисный бот проекта Pbm5_5 FZ-LLC для поиска в Яндекс Музыке и VK Музыке.",
    hero_btn_bot: "Открыть бота",
    hero_btn_charts: "Смотреть чарты",
    about_title: "Как это работает",
    about_desc: "Наш бот упрощает процесс поиска музыки. Забудьте о переключении между приложениями.",
    step_1_title: "Запустите бота",
    step_1_desc: "Откройте Telegram и нажмите Start.",
    step_2_title: "Введите название",
    step_2_desc: "Напишите название трека или имя исполнителя.",
    step_3_title: "Получите результат",
    step_3_desc: "Слушайте музыку из Yandex и VK мгновенно.",
    features_title: "Почему выбирают нас",
    feat_instant_title: "Мгновенный поиск",
    feat_instant_desc: "Высокая скорость обработки запросов без задержек.",
    feat_sources_title: "Две платформы",
    feat_sources_desc: "Поиск одновременно в базах Яндекс Музыки и VK Музыки.",
    feat_charts_title: "Топ-чарты",
    feat_charts_desc: "Актуальные рейтинги самых популярных треков.",
    feat_support_title: "Поддержка 24/7",
    feat_support_desc: "Наша команда всегда готова помочь с любыми вопросами.",
    charts_title: "Популярное сейчас",
    charts_tab_yandex: "Яндекс Музыка",
    charts_tab_vk: "VK Музыка",
    contact_title: "Свяжитесь с нами",
    contact_company: "Компания",
    contact_phone: "Телефон колл-центра",
    contact_email: "Email",
    contact_tg_support: "Поддержка Telegram",
    contact_tt_support: "Поддержка TamTam",
    footer_rights: "Все права защищены.",
    footer_policy: "Политика конфиденциальности",
    footer_terms: "Пользовательское соглашение"
  },
  [Language.EN]: {
    nav_home: "Home",
    nav_about: "About",
    nav_features: "Features",
    nav_charts: "Top Charts",
    nav_contact: "Contact",
    hero_title: "MusicSearch Ru — Fast Music Search",
    hero_subtitle: "Official service bot by Pbm5_5 FZ-LLC for searching in Yandex Music and VK Music.",
    hero_btn_bot: "Open Bot",
    hero_btn_charts: "View Charts",
    about_title: "How it works",
    about_desc: "Our bot simplifies the music search process. Forget about switching between apps.",
    step_1_title: "Start the bot",
    step_1_desc: "Open Telegram and press Start.",
    step_2_title: "Type the name",
    step_2_desc: "Enter a track title or artist name.",
    step_3_title: "Get results",
    step_3_desc: "Listen to music from Yandex and VK instantly.",
    features_title: "Why choose us",
    feat_instant_title: "Instant Search",
    feat_instant_desc: "High-speed request processing without delays.",
    feat_sources_title: "Two Platforms",
    feat_sources_desc: "Search simultaneously in Yandex Music and VK Music databases.",
    feat_charts_title: "Top Charts",
    feat_charts_desc: "Up-to-date rankings of the most popular tracks.",
    feat_support_title: "24/7 Support",
    feat_support_desc: "Our team is always ready to help with any questions.",
    charts_title: "Trending Now",
    charts_tab_yandex: "Yandex Music",
    charts_tab_vk: "VK Music",
    contact_title: "Contact Us",
    contact_company: "Company",
    contact_phone: "Call Center",
    contact_email: "Email",
    contact_tg_support: "Telegram Support",
    contact_tt_support: "TamTam Support",
    footer_rights: "All rights reserved.",
    footer_policy: "Privacy Policy",
    footer_terms: "User Agreement"
  },
  [Language.UZ_LAT]: {
    nav_home: "Bosh sahifa",
    nav_about: "Bot haqida",
    nav_features: "Imkoniyatlar",
    nav_charts: "Top-chartlar",
    nav_contact: "Aloqa",
    hero_title: "MusicSearch Ru — Musiqani tezkor qidirish",
    hero_subtitle: "Pbm5_5 FZ-LLC loyihasining Yandex Music va VK Music-da qidirish uchun rasmiy boti.",
    hero_btn_bot: "Botni ochish",
    hero_btn_charts: "Chartlarni ko'rish",
    about_title: "Bu qanday ishlaydi",
    about_desc: "Bizning botimiz musiqa qidirish jarayonini soddalashtiradi. Ilovalar o'rtasida almashishni unuting.",
    step_1_title: "Botni ishga tushiring",
    step_1_desc: "Telegramni oching va Start tugmasini bosing.",
    step_2_title: "Nomini kiriting",
    step_2_desc: "Trek nomini yoki ijrochi ismini yozing.",
    step_3_title: "Natijani oling",
    step_3_desc: "Yandex va VK-dan musiqani darhol tinglang.",
    features_title: "Nima uchun bizni tanlashadi",
    feat_instant_title: "Tezkor qidiruv",
    feat_instant_desc: "So'rovlarni kechikishsiz yuqori tezlikda qayta ishlash.",
    feat_sources_title: "Ikki platforma",
    feat_sources_desc: "Bir vaqtning o'zida Yandex Music va VK Music bazalarida qidirish.",
    feat_charts_title: "Top-chartlar",
    feat_charts_desc: "Eng mashhur treklarning dolzarb reytinglari.",
    feat_support_title: "24/7 Qo'llab-quvvatlash",
    feat_support_desc: "Bizning jamoamiz har qanday savollar bilan yordam berishga tayyor.",
    charts_title: "Hozir ommabop",
    charts_tab_yandex: "Yandex Music",
    charts_tab_vk: "VK Music",
    contact_title: "Biz bilan bog'laning",
    contact_company: "Kompaniya",
    contact_phone: "Call-markaz",
    contact_email: "Email",
    contact_tg_support: "Telegram yordam",
    contact_tt_support: "TamTam yordam",
    footer_rights: "Barcha huquqlar himoyalangan.",
    footer_policy: "Maxfiylik siyosati",
    footer_terms: "Foydalanuvchi shartnomasi"
  },
  [Language.UZ_CYR]: {
    nav_home: "Бош саҳифа",
    nav_about: "Бот ҳақида",
    nav_features: "Имкониятлар",
    nav_charts: "Топ-чартлар",
    nav_contact: "Алоқа",
    hero_title: "MusicSearch Ru — Мусиқани тезкор қидириш",
    hero_subtitle: "Pbm5_5 FZ-LLC лойиҳасининг Yandex Music ва VK Music-да қидириш учун расмий боти.",
    hero_btn_bot: "Ботни очиш",
    hero_btn_charts: "Чартларни кўриш",
    about_title: "Бу қандай ишлайди",
    about_desc: "Бизнинг ботимиз мусиқа қидириш жараёнини соддалаштиради. Иловалар ўртасида алмашишни унутинг.",
    step_1_title: "Ботни ишга туширинг",
    step_1_desc: "Telegramни очинг ва Start тугмасини босинг.",
    step_2_title: "Номини киритинг",
    step_2_desc: "Трек номини ёки ижрочи исмини ёзинг.",
    step_3_title: "Натижани олинг",
    step_3_desc: "Yandex ва VK-дан мусиқани дарҳол тингланг.",
    features_title: "Нима учун бизни танлашади",
    feat_instant_title: "Тезкор қидирув",
    feat_instant_desc: "Сўровларни кечикишсиз юқори тезликда қайта ишлаш.",
    feat_sources_title: "Икки платформа",
    feat_sources_desc: "Бир вақтнинг ўзида Yandex Music ва VK Music базаларида қидириш.",
    feat_charts_title: "Топ-чартлар",
    feat_charts_desc: "Энг машҳур трекларнинг долзарб рейтинглари.",
    feat_support_title: "24/7 Қўллаб-қувватлаш",
    feat_support_desc: "Бизнинг жамоамиз ҳар қандай саволлар билан ёрдам беришга тайёр.",
    charts_title: "Ҳозир оммабоп",
    charts_tab_yandex: "Yandex Music",
    charts_tab_vk: "VK Music",
    contact_title: "Биз билан боғланинг",
    contact_company: "Компания",
    contact_phone: "Call-марказ",
    contact_email: "Email",
    contact_tg_support: "Telegram ёрдам",
    contact_tt_support: "TamTam ёрдам",
    footer_rights: "Барча ҳуқуқлар ҳимояланган.",
    footer_policy: "Махфийлик сиёсати",
    footer_terms: "Фойдаланувчи шартномаси"
  }
};

export const CONTACT_INFO = {
  companyName: "Pbm5_5 FZ-LLC",
  phone: "+998-88-878-06-09",
  emails: ["pbm5_5@outlook.com", "pbm5_5@yahoo.com"],
  botLink: "https://t.me/musicsearchrubot",
  tgSupport: "https://t.me/pbm5_5_support_bot",
  ttSupport: "https://tt.me/pbm5_5_support_bot"
};

export const MOCK_CHART_YANDEX: Song[] = [
  { rank: 1, title: "Царица", artist: "ANNA ASTI", cover: "https://picsum.photos/id/10/80/80" },
  { rank: 2, title: "На заре", artist: "Basta", cover: "https://picsum.photos/id/12/80/80" },
  { rank: 3, title: "Пыяла", artist: "AIGEL", cover: "https://picsum.photos/id/15/80/80" },
  { rank: 4, title: "Где прошла ты", artist: "Кравц, Гио Пика", cover: "https://picsum.photos/id/20/80/80" },
  { rank: 5, title: "Зима в сердце", artist: "Моя Мишель", cover: "https://picsum.photos/id/25/80/80" },
];

export const MOCK_CHART_VK: Song[] = [
  { rank: 1, title: "Давай сбежим", artist: "5УТРА", cover: "https://picsum.photos/id/30/80/80" },
  { rank: 2, title: "АСФАЛЬТ", artist: "JAKONE, KILIANA", cover: "https://picsum.photos/id/34/80/80" },
  { rank: 3, title: "За деньги да", artist: "INSTASAMKA", cover: "https://picsum.photos/id/42/80/80" },
  { rank: 4, title: "Стрелы", artist: "Markul, Тося Чайкина", cover: "https://picsum.photos/id/48/80/80" },
  { rank: 5, title: "Худи", artist: "Джиган, Artik & Asti", cover: "https://picsum.photos/id/55/80/80" },
];
